---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yogantee/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp Yoganteek_Corporate_Landing_Page.html $DEPLOYPATH
